version: '3.9'

services:
  # USER SERVICE
  user-service:
    build: ./user-service
    container_name: user-service
    ports:
      - "8000:8000"
    depends_on:
      - user-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@user-db:5432/user_db
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30

  user-db:
    image: postgres:15
    container_name: user-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: user_db
    ports:
      - "5432:5432"
    volumes:
      - user-db-data:/var/lib/postgresql/data

  # BOOK SERVICE
  book-service:
    build: ./book-service
    container_name: book-service
    ports:
      - "8001:8001"
    depends_on:
      - book-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@book-db:5432/book_db

  book-db:
    image: postgres:15
    container_name: book-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: book_db
    ports:
      - "5433:5432"
    volumes:
      - book-db-data:/var/lib/postgresql/data

  # REVIEW SERVICE
  review-service:
    build: ./review-service
    container_name: review-service
    ports:
      - "8002:8002"
    depends_on:
      - review-db
    environment:
      - DATABASE_URL=postgresql+asyncpg://postgres:password@review-db:5432/review_db
      - SECRET_KEY=supersecretkey
      - ALGORITHM=HS256

  review-db:
    image: postgres:15
    container_name: review-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: review_db
    ports:
      - "5434:5432"
    volumes:
      - review-db-data:/var/lib/postgresql/data

volumes:
  user-db-data:
  book-db-data:
  review-db-data:

